# Generated by Django 5.2 on 2025-04-17 06:26

from django.db import migrations
import os 


def create_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')

    User.objects.create_user(
        username='admin',
        password=os.getenv('ADMIN_PASSWORD'),
        is_staff=True,
        is_superuser=False
    )

    User.objects.create_user(
        username='pharmacist',
        password=os.getenv('PHARMACIST_PASSWORD'),
        is_staff=False,
        is_superuser=False
    )

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_users),
    ]
