# Generated by Django 5.2 on 2025-04-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('good_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('su_name', models.TextField()),
                ('group', models.TextField()),
                ('prep', models.TextField()),
                ('level', models.TextField()),
                ('type', models.TextField()),
                ('sort_order', models.BigIntegerField()),
            ],
            options={
                'db_table': 'core_prep_variants',
                'db_table_comment': 'core',
                'managed': False,
            },
        ),
    ]
